### ISSUE TITLE
Stop builds if a build fails

### ISSUE THREAD

**Issue by AlexU-A** [ProboCI/probo#119]
In order to prevent deployments or other build steps, it would be great to have the option to stop the build process upon receiving an error.

Current behavior:
In some cases when a build step fails, for example when a behat test fails, the build process continues to the next step.

Proposed behavior:
Allow a configuration option that denotes when an error in a build step should terminate the process.

**Comment by tortillaj** [comment]
I think we should expand upon this idea a bit. Additionally, we add lifecycle hooks:

```
steps:
  .......
after_success:
  - command: .....
after_fail:
  - command: ...
```
