### ISSUE TITLE
Drupal plugin not correctly identifying database

### ISSUE THREAD

**Issue by tortillaj** [ProboCI/probo#60]
In this sample probo config, the database `old-database.sql.gz` is correctly identified and downloaded during site building, but `new-database.sql.gz` is not!

```
assets:
  - old-database.sql.gz
steps:
  - name: Setup Drupal site
    plugin: Drupal
    database: new-database.sql.gz
    subDirectory: public
    databaseGzipped: true
    databaseUpdates: true
    revertFeatures: true
```

To make this work properly, you must specify the database in both locations:

```
assets:
  - new-database.sql.gz
steps:
  - name: Setup Drupal site
    plugin: Drupal
    database: new-database.sql.gz
    subDirectory: public
    databaseGzipped: true
    databaseUpdates: true
    revertFeatures: true
```
